# .github/workflows/pacman.yml
name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate Light Mode Pacman Graph
        uses: platane/platane-pacman@v1
        with:
          github_user_name: "ZUD012"
          # The file for light mode
          file_path: pacman-contribution-graph.svg
          # The branch where BOTH files will be saved
          target_branch: output 

      - name: Generate Dark Mode Pacman Graph
        uses: platane/platane-pacman@v1
        with:
          github_user_name: "ZUD012"
          # The file for dark mode
          file_path: pacman-contribution-graph-dark.svg
          # The branch where BOTH files will be saved
          target_branch: output
          # Built-in dark theme
          theme: "dracula"
