# .github/workflows/pacman.yml
name: Generate Pacman Contribution Graph

on:
  # This will run the action every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # This allows you to run the action manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man Contribution Graph
        uses: platane/platane-pacman@v1
        with:
          # Your GitHub username
          github_user_name: "ZUD012"
          
          # The branch where the file will be saved
          target_branch: main

          # The name of the file to be generated
          file_path: pacman-contribution-graph.svg
